#!/opt/local/bin/python
# -*- coding: utf-8 -*-
from tempfile import mkstemp
from shutil import move
from os import fdopen, remove
from datetime import datetime

def replace(file_path, pattern, subst):
  # create temp file
  fh, abs_path = mkstemp()
  with fdopen(fh,'w') as new_file:
    with open(file_path) as old_file:
      new_file.write(old_file.read().replace(pattern, subst))
  # remove original file
  remove(file_path)
  # move new file
  move(abs_path, file_path)

def postdate(post_path):
  with open(post_path) as postfile:
    for line in postfile:
      if '<h5>' in line:
	return line[line.index('<h5>')+4:line.rindex('</h5>')]

# --- main ---

enmonth = ["0", "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
plmonth = ["0", "Sty", "Lut", "Mar", "Kwi", "Maj", "Cze", "Lip", "Sie", "Wrz", "Paz", "Lis", "Gru"]
now = datetime.now() # now.year, now.month, now.day, now.hour, now.minute, now.second

with open('en/writing.html') as enindex:
  for line in enindex:
    if ('post-' in line): # find most recent post
      post0en = line[line.index('"')+1:line.rindex('"')]
      post0pl = post0en.replace('post','wpis').replace('writing','pisanie')
      lastnum = int(line[line.rindex('-')+1:line.rindex('.')])
      break

path0en = 'en/' + post0en
path0pl = 'pl/' + post0pl
date0en = postdate(path0en)
date0pl = postdate(path0pl)
date1en = enmonth[now.month] + ' %d, %d' % (now.day, now.year)
date1pl = plmonth[now.month] + ' %d, %d' % (now.day, now.year)

print('Updating ' + path0en + ' to ' + date1en)
replace(path0en, date0en, date1en)
replace('en/writing.html', date0en, date1en)

print('Updating ' + path0pl + ' to ' + date1pl)
replace(path0pl, date0pl, date1pl)
replace('pl/pisanie.html', date0pl, date1pl)
